#!python3

from datetime import datetime
from datetime import date

datetime.today()
#datetime.datetime(2019, 2, 14, 11, 29, 0, 722760)

today = datetime.today()


type(today)
#<class 'datetime.datetime'>


todaydate = date.today()

todaydate
#datetime.date(2019, 2, 14)

type(todaydate)
#<class 'datetime.date'>

todaydate.month
#2

todaydate.year
#2019

todaydate.day
#14


christmas = date(2019, 12, 25)
christmas
#datetime.date(2019, 12, 25)

if christmas is not todaydate:
    print("Sorry there are still " + str((christmas - todaydate).days) + " until Christmas!")
else:
    print("Yay it's Christmas!")
